#!/usr/bin/python
# This file is automatically generated by symbiotic-build.sh

versions = {
	'symbiotic' : 'f20a9385604cff376e14e18054f84ad952c612b8',
	'dg' : 'acf28d43c9432a78cfb5acde1e730fdbb30147c3',
	'sbt-slicer' : 'ec203338e77b3ff45b7c34bc84715a24723b9a51',
	'sbt-instrumentation' : '1411d529151c5399bdefa49235e4317b2255d338',
	'klee' : 'a49866ed96ff0bf373718953bedf27f9ec7b1d56',
}

llvm_version = '10.0.0'

build_types = {
	'symbiotic' : 'Release',
	'dg' : 'Release',
	'sbt-slicer' : 'Release',
	'sbt-instrumentation' : 'Release',
	'klee' : 'Release',
	'klee-runtime' : 'Release',
}

